[versions]
composeVectorize = "1.3.0"
dependencyGraphGenerator = "0.8.0"
fonament = "0.0.1-alpha07"
jdk = "21"
navigationComposeExtended = "1.6.2"
pigment = "0.7.0"

[libraries]
dependencyGraphGenerator = { module = "com.vanniktech:gradle-dependency-graph-generator-plugin", version.ref = "dependencyGraphGenerator" }

sergiobelda-composeVectorize-core = { module = "dev.sergiobelda.compose.vectorize:compose-vectorize-core", version.ref = "composeVectorize" }
sergiobelda-fonament-preferences = { module = "dev.sergiobelda.fonament:fonament-preferences", version.ref = "fonament" }
sergiobelda-fonament-preferencesDiKoin = { module = "dev.sergiobelda.fonament:fonament-preferences-di-koin", version.ref = "fonament" }
sergiobelda-fonament-presentation = { module = "dev.sergiobelda.fonament:fonament-presentation", version.ref = "fonament" }
sergiobelda-fonament-presentationDiKoin = { module = "dev.sergiobelda.fonament:fonament-presentation-di-koin", version.ref = "fonament" }
sergiobelda-navigationComposeExtended = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedAnnotation = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-annotation", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedCompiler = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-compiler", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedWear = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-wear", version.ref = "navigationComposeExtended" }
sergiobelda-pigment = { module = "dev.sergiobelda.pigment:pigment", version.ref = "pigment" }

[plugins]
dependencyGraphGenerator = { id = "com.vanniktech.dependency.graph.generator", version.ref = "dependencyGraphGenerator" }
sergiobelda-composeVectorize = { id = "dev.sergiobelda.compose.vectorize", version.ref = "composeVectorize" }

sergiobelda-gradle-common-library-android = { id = "dev.sergiobelda.gradle.common.library.android" }
sergiobelda-gradle-common-ui = { id = "dev.sergiobelda.gradle.common.ui" }
sergiobelda-gradle-common-uiToolingPreview = { id = "dev.sergiobelda.gradle.common.ui.tooling.preview" }
sergiobelda-gradle-dependencyGraphGenerator = { id = "dev.sergiobelda.gradle.dependency-graph-generator" }
