name: Build Project

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle  
    - name: Create google-services.json in app-android
      run:  echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app-android/google-services.json
    - name: Create google-services.json in wearapp-wearos
      run:  echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > wearapp-wearos/google-services.json
    - name: Run spotlessCheck
      run: ./gradlew spotlessCheck
    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest
    - name: Build app-android
      run:  ./gradlew app-android:assembleDebug
    - name: Build app-desktop
      run:  ./gradlew app-desktop:assemble
    - name: Build app-ios
      run:  ./gradlew assembleXCFramework
    - name: Build wearapp-wearos
      run:  ./gradlew wearapp-wearos:assembleDebug
