name: Deploy ToDometer Android App to Alpha

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble Release Bundle
        run: ./gradlew android:bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
      - name: Deploy to Develop
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: service_account.json
          packageName: dev.sergiobelda.todometer
          releaseFile: android/build/outputs/bundle/release/android-release.aab
          track: alpha
      - name: Tag Release
        run: |
          version_name=${{ github.event.inputs.versionName }}
          echo "Tagging release with tag $version_name"
          git tag android-$version_name
          git push origin --tags
